### ISSUE TITLE
need EGL_KHR_surfaceless_context extension

### ISSUE THREAD

**Issue by Chinggis6** [sonald/blur-effect#2]
I get the following error for `blur_effect img.png -o blur_img.png`:

```
image has no alpha
try to open /dev/dri/renderD128
backend name: drm
need EGL_KHR_surfaceless_context extension

```
I use Arch Linux and installed the program from Community repository as [`blur-effect`](https://www.archlinux.org/packages/community/x86_64/blur-effect/) package.

**Comment by sonald** [comment]
I don't know where is this blur_effect command comes from, I think it's blur_image? use `blur_image -d /dev/dri/renderD128  img.png -o blur_img.png` if under X11, or just `sudo blur_image img.png -o blur_img.png`. if neither works, plz paste output of `glxinfo` here.
